"""LangGraph Network Automation and Self-Healing Agent.

Autonomous network operations prototype integrating LangGraph state machine,
Containerlab runtime environment, and fine-tuned Qwen model interactions.
"""

__version__ = "0.1.0"

from langgraph_netagent.models import (
    ConfigurationPatch,
    ContainerlabLinkEndpoint,
    ContainerlabMgmtConfig,
    ContainerlabNodeConfig,
    ContainerlabTopologyFile,
    DeviceConfigFile,
    DiagnosticReport,
    ErrorCategory,
    FullTopologyPackage,
    IPAllocation,
    InterfaceTelemetry,
    LinkIntent,
    NetworkHealthReport,
    NetworkIntent,
    NodeIntent,
    PingTelemetry,
    RemediationActionType,
    RemediationPlan,
    RollbackStep,
    RouteEntry,
    RouteTableTelemetry,
    SeverityLevel,
    ValidationErrorDetail,
    ValidationResult,
    ValidationSeverity,
    # Milestone 2 Intent Models
    CanonicalIntent,
    CanonicalRemediationIntent,
    CompilationResult,
    CompiledRemediationResult,
    IntentAction,
    IntentActionType,
    PlatformType,
    TargetPlatform,
    # Milestone 3 Knowledge Models
    DualRetrievalResult,
    TreeNode,
    VectorIndexEntry,
    VendorDocSource,
)
from langgraph_netagent.tools import (
    BaseNetworkLabAdapter,
    CommandResult,
    DeploymentResult,
    DestructionResult,
    EnvironmentCapabilities,
    EnvironmentDetector,
    ExecutionMode,
    FaultInjector,
    FaultRule,
    FaultType,
    InterfaceProbe,
    LabInspectionResult,
    LabNodeState,
    LiveContainerlabAdapter,
    MockContainerlabAdapter,
    MockEngine,
    NetworkTelemetryCollector,
    PingProbe,
    RouteTableProbe,
    SubprocessRunner,
    TopologyExporter,
    VirtualNetworkGraph,
    WSLBridgeRunner,
    # AAL & Sandbox
    AALSecurityError,
    AgentAccessLayer,
    AutoGarbageCollector,
    DockerSandboxRuntime,
    MockSandboxRuntime,
    ShadowSandboxManager,
    SOPDocument,
    SOPRetriever,
    create_sandbox_runtime,
    # Intent Compiler
    CanonicalIntentCompiler,
    compile_canonical_intent,
    compile_remediation_plan,
    # Milestone 3 Vendor Knowledge & Dual-Retrieval
    CommandTreeStore,
    DualRetrievalEngine,
    LightweightVectorIndex,
    VendorDocIngestor,
)
from langgraph_netagent.models.operational import (
    AALResponse,
    AALToolCall,
    FiveTuple,
    InventoryPool,
    NetworkDiscrepancy,
    ShadowSandboxResult,
)
from langgraph_netagent.models.sandbox import (
    GCReport,
    PreflightSandboxPassReport,
    ResourceQuota,
    SandboxExecutionResult,
)
from langgraph_netagent.validation import OfflineValidator
from langgraph_netagent.workflow import (
    END,
    START,
    CompiledSimpleGraph,
    LogEntry,
    NetworkAgentState,
    SimpleMemorySaver,
    SimpleStateGraph,
    build_network_agent_graph,
    create_initial_state,
    create_log_entry,
    create_workflow_nodes,
    route_after_approval,
    route_after_deployment,
    route_after_validation,
    route_after_verification,
    run_network_agent_workflow,
    # Operational workflow
    OperationalState,
    build_operational_graph,
    create_operational_initial_state,
    create_operational_nodes,
    run_operational_workflow,
    # Harmonized workflow (Milestone 5)
    HarmonizedOperationalGraph,
    HarmonizedGraph,
    HarmonizedState,
    HarmonizedOpsState,
    OperationalPhase,
    build_harmonized_graph,
    create_harmonized_initial_state,
    create_harmonized_nodes,
    run_harmonized_workflow,
)
from langgraph_netagent.execution_logger import (
    ExecutionLogEntry,
    ExecutionLogger,
    get_execution_logger,
    log_execution,
    wrap_logged_nodes,
)

__all__ = [
    "__version__",
    "NetworkIntent",
    "NodeIntent",
    "LinkIntent",
    "ContainerlabTopologyFile",
    "ContainerlabNodeConfig",
    "ContainerlabLinkEndpoint",
    "ContainerlabMgmtConfig",
    "DeviceConfigFile",
    "FullTopologyPackage",
    "IPAllocation",
    "ValidationResult",
    "ValidationErrorDetail",
    "ValidationSeverity",
    "DiagnosticReport",
    "ErrorCategory",
    "SeverityLevel",
    "RemediationPlan",
    "RemediationActionType",
    "ConfigurationPatch",
    "RollbackStep",
    "PingTelemetry",
    "RouteEntry",
    "RouteTableTelemetry",
    "InterfaceTelemetry",
    "NetworkHealthReport",
    # Tools
    "BaseNetworkLabAdapter",
    "CommandResult",
    "DeploymentResult",
    "DestructionResult",
    "LabInspectionResult",
    "LabNodeState",
    "ExecutionMode",
    "EnvironmentCapabilities",
    "EnvironmentDetector",
    "SubprocessRunner",
    "WSLBridgeRunner",
    "FaultType",
    "FaultRule",
    "FaultInjector",
    "VirtualNetworkGraph",
    "MockEngine",
    "MockContainerlabAdapter",
    "LiveContainerlabAdapter",
    "TopologyExporter",
    "PingProbe",
    "RouteTableProbe",
    "InterfaceProbe",
    "NetworkTelemetryCollector",
    # Validation
    "OfflineValidator",
    # Workflow
    "NetworkAgentState",
    "LogEntry",
    "create_initial_state",
    "create_log_entry",
    "create_workflow_nodes",
    "route_after_validation",
    "route_after_approval",
    "route_after_deployment",
    "route_after_verification",
    "build_network_agent_graph",
    "run_network_agent_workflow",
    "SimpleStateGraph",
    "CompiledSimpleGraph",
    "SimpleMemorySaver",
    "START",
    "END",
    # Operational NetOps Workflow & AAL
    "FiveTuple",
    "InventoryPool",
    "NetworkDiscrepancy",
    "AALToolCall",
    "AALResponse",
    "AALSecurityError",
    "AgentAccessLayer",
    "ShadowSandboxManager",
    "ShadowSandboxResult",
    "DockerSandboxRuntime",
    "MockSandboxRuntime",
    "AutoGarbageCollector",
    "create_sandbox_runtime",
    "ResourceQuota",
    "SandboxExecutionResult",
    "GCReport",
    "PreflightSandboxPassReport",
    "SOPDocument",
    "SOPRetriever",
    # Milestone 2 Intent Models & Compiler
    "IntentAction",
    "IntentActionType",
    "TargetPlatform",
    "PlatformType",
    "CanonicalIntent",
    "CanonicalRemediationIntent",
    "CompilationResult",
    "CompiledRemediationResult",
    "CanonicalIntentCompiler",
    "compile_canonical_intent",
    "compile_remediation_plan",
    # Milestone 3 Vendor Knowledge & Dual-Retrieval
    "TreeNode",
    "VectorIndexEntry",
    "DualRetrievalResult",
    "VendorDocSource",
    "CommandTreeStore",
    "LightweightVectorIndex",
    "VendorDocIngestor",
    "DualRetrievalEngine",
    # Operational workflow
    "OperationalState",
    "build_operational_graph",
    "run_operational_workflow",
    "create_operational_initial_state",
    "create_operational_nodes",
    # Harmonized workflow (Milestone 5)
    "HarmonizedOperationalGraph",
    "HarmonizedGraph",
    "HarmonizedState",
    "HarmonizedOpsState",
    "OperationalPhase",
    "build_harmonized_graph",
    "run_harmonized_workflow",
    "create_harmonized_initial_state",
    "create_harmonized_nodes",
    # Execution Logger and Audit Tracer
    "ExecutionLogEntry",
    "ExecutionLogger",
    "get_execution_logger",
    "log_execution",
    "wrap_logged_nodes",
]

