"""LangGraph Network Automation and Self-Healing Agent.

Autonomous network operations prototype integrating LangGraph state machine,
Containerlab runtime environment, and fine-tuned Qwen model interactions.
"""

__version__ = "0.1.0"

from langgraph_netagent.models import (
    ConfigurationPatch,
    ContainerlabLinkEndpoint,
    ContainerlabMgmtConfig,
    ContainerlabNodeConfig,
    ContainerlabTopologyFile,
    DeviceConfigFile,
    DiagnosticReport,
    ErrorCategory,
    FullTopologyPackage,
    IPAllocation,
    InterfaceTelemetry,
    LinkIntent,
    NetworkHealthReport,
    NetworkIntent,
    NodeIntent,
    PingTelemetry,
    RemediationActionType,
    RemediationPlan,
    RollbackStep,
    RouteEntry,
    RouteTableTelemetry,
    SeverityLevel,
    ValidationErrorDetail,
    ValidationResult,
    ValidationSeverity,
)
from langgraph_netagent.tools import (
    BaseNetworkLabAdapter,
    CommandResult,
    DeploymentResult,
    DestructionResult,
    EnvironmentCapabilities,
    EnvironmentDetector,
    ExecutionMode,
    FaultInjector,
    FaultRule,
    FaultType,
    InterfaceProbe,
    LabInspectionResult,
    LabNodeState,
    LiveContainerlabAdapter,
    MockContainerlabAdapter,
    MockEngine,
    NetworkTelemetryCollector,
    PingProbe,
    RouteTableProbe,
    SubprocessRunner,
    TopologyExporter,
    VirtualNetworkGraph,
    WSLBridgeRunner,
    # AAL & Sandbox
    AALSecurityError,
    AgentAccessLayer,
    ShadowSandboxManager,
    SOPDocument,
    SOPRetriever,
)
from langgraph_netagent.models.operational import (
    AALResponse,
    AALToolCall,
    FiveTuple,
    InventoryPool,
    NetworkDiscrepancy,
    ShadowSandboxResult,
)
from langgraph_netagent.validation import OfflineValidator
from langgraph_netagent.workflow import (
    END,
    START,
    CompiledSimpleGraph,
    LogEntry,
    NetworkAgentState,
    SimpleMemorySaver,
    SimpleStateGraph,
    build_network_agent_graph,
    create_initial_state,
    create_log_entry,
    create_workflow_nodes,
    route_after_approval,
    route_after_deployment,
    route_after_validation,
    route_after_verification,
    run_network_agent_workflow,
    # Operational workflow
    OperationalState,
    build_operational_graph,
    create_operational_initial_state,
    create_operational_nodes,
    run_operational_workflow,
)

__all__ = [
    "__version__",
    "NetworkIntent",
    "NodeIntent",
    "LinkIntent",
    "ContainerlabTopologyFile",
    "ContainerlabNodeConfig",
    "ContainerlabLinkEndpoint",
    "ContainerlabMgmtConfig",
    "DeviceConfigFile",
    "FullTopologyPackage",
    "IPAllocation",
    "ValidationResult",
    "ValidationErrorDetail",
    "ValidationSeverity",
    "DiagnosticReport",
    "ErrorCategory",
    "SeverityLevel",
    "RemediationPlan",
    "RemediationActionType",
    "ConfigurationPatch",
    "RollbackStep",
    "PingTelemetry",
    "RouteEntry",
    "RouteTableTelemetry",
    "InterfaceTelemetry",
    "NetworkHealthReport",
    # Tools
    "BaseNetworkLabAdapter",
    "CommandResult",
    "DeploymentResult",
    "DestructionResult",
    "LabInspectionResult",
    "LabNodeState",
    "ExecutionMode",
    "EnvironmentCapabilities",
    "EnvironmentDetector",
    "SubprocessRunner",
    "WSLBridgeRunner",
    "FaultType",
    "FaultRule",
    "FaultInjector",
    "VirtualNetworkGraph",
    "MockEngine",
    "MockContainerlabAdapter",
    "LiveContainerlabAdapter",
    "TopologyExporter",
    "PingProbe",
    "RouteTableProbe",
    "InterfaceProbe",
    "NetworkTelemetryCollector",
    # Validation
    "OfflineValidator",
    # Workflow
    "NetworkAgentState",
    "LogEntry",
    "create_initial_state",
    "create_log_entry",
    "create_workflow_nodes",
    "route_after_validation",
    "route_after_approval",
    "route_after_deployment",
    "route_after_verification",
    "build_network_agent_graph",
    "run_network_agent_workflow",
    "SimpleStateGraph",
    "CompiledSimpleGraph",
    "SimpleMemorySaver",
    "START",
    "END",
    # Operational NetOps Workflow & AAL
    "FiveTuple",
    "InventoryPool",
    "NetworkDiscrepancy",
    "AALToolCall",
    "AALResponse",
    "AALSecurityError",
    "AgentAccessLayer",
    "ShadowSandboxManager",
    "ShadowSandboxResult",
    "SOPDocument",
    "SOPRetriever",
    "OperationalState",
    "build_operational_graph",
    "run_operational_workflow",
    "create_operational_initial_state",
    "create_operational_nodes",
]

