"""Sandbox and container isolation models for LangGraph NetAgent.

Defines resource quotas, execution telemetry, garbage collection reporting,
and pre-flight sandbox pass reports for isolated verification before HITL.
"""

from __future__ import annotations

from datetime import datetime, timezone
import hashlib
import json
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class ResourceQuota(BaseModel):
    """Resource constraints enforced on isolated sandbox containers via cgroups."""

    nano_cpus: int = Field(
        default=1_000_000_000,
        description="CPU quota in nano-CPUs (1_000_000_000 = 1.0 CPU core)",
    )
    mem_limit: str = Field(
        default="512m",
        description="Maximum memory limit (e.g. '512m')",
    )
    pids_limit: int = Field(
        default=100,
        description="Maximum process limit to prevent fork bombs",
    )
    tmpfs_size: str = Field(
        default="64m",
        description="Ephemeral tmpfs size for scratch files (e.g. '64m')",
    )

    def to_docker_flags(self) -> List[str]:
        """Convert quota to docker run CLI argument flags."""
        cpu_cores = self.nano_cpus / 1_000_000_000
        return [
            f"--cpus={cpu_cores:.2f}".rstrip("0").rstrip("."),
            f"--memory={self.mem_limit}",
            f"--memory-swap={self.mem_limit}",
            f"--pids-limit={self.pids_limit}",
            f"--tmpfs=/tmp:rw,size={self.tmpfs_size},mode=1777",
        ]

    def to_docker_kwargs(self) -> Dict[str, Any]:
        """Convert quota to docker SDK container instantiation kwargs."""
        return {
            "nano_cpus": self.nano_cpus,
            "mem_limit": self.mem_limit,
            "memswap_limit": self.mem_limit,
            "pids_limit": self.pids_limit,
            "tmpfs": {"/tmp": f"rw,size={self.tmpfs_size},mode=1777"},
        }

    def to_dict(self) -> Dict[str, Any]:
        """Export quota dictionary matching PROJECT.md interface contract."""
        return {
            "cpu_limit": f"{self.nano_cpus / 1_000_000_000:.1f}",
            "nano_cpus": self.nano_cpus,
            "mem_limit": self.mem_limit,
            "pids_limit": self.pids_limit,
            "tmpfs_size": self.tmpfs_size,
        }


class SandboxExecutionResult(BaseModel):
    """Execution telemetry captured from a command run inside an isolated sandbox."""

    exit_code: int = Field(..., description="Process exit code (0 indicates success)")
    stdout: str = Field(default="", description="Captured standard output")
    stderr: str = Field(default="", description="Captured standard error")
    duration_sec: float = Field(default=0.0, description="Execution duration in seconds")
    timed_out: bool = Field(default=False, description="True if command timed out")
    command: str = Field(default="", description="Command that was executed")
    sandbox_id: Optional[str] = Field(default=None, description="Identifier of the sandbox container")
    target_node: Optional[str] = Field(default=None, description="Target network node identifier")
    resource_usage: Optional[Dict[str, Any]] = Field(default=None, description="Resource utilization metrics")

    @property
    def duration_seconds(self) -> float:
        """Alias for duration_sec for backward and forward compatibility."""
        return self.duration_sec

    @property
    def is_timeout(self) -> bool:
        """Alias for timed_out."""
        return self.timed_out

    @property
    def success(self) -> bool:
        """Convenience property for exit_code == 0 and not timed_out."""
        return self.exit_code == 0 and not self.timed_out


class GCReport(BaseModel):
    """Report generated by the automated sandbox garbage collector."""

    containers_removed: List[str] = Field(
        default_factory=list,
        description="IDs or names of orphaned containers force-removed",
    )
    images_pruned: List[str] = Field(
        default_factory=list,
        description="IDs or tags of untagged/dangling images pruned",
    )
    reclaimed_bytes: int = Field(
        default=0,
        description="Estimated disk space reclaimed in bytes",
    )
    errors: List[str] = Field(
        default_factory=list,
        description="Non-fatal warning or error messages encountered during GC",
    )
    scanned_containers_count: int = Field(
        default=0,
        description="Total number of labeled sandbox containers scanned",
    )
    timestamp: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat(),
        description="UTC timestamp of GC execution",
    )

    @property
    def removed_containers(self) -> List[str]:
        """Alias for containers_removed."""
        return self.containers_removed

    @property
    def pruned_images(self) -> List[str]:
        """Alias for images_pruned."""
        return self.images_pruned


class PreflightSandboxPassReport(BaseModel):
    """Certified pre-flight sandbox pass report gating Human-in-the-Loop (HITL) approval."""

    sandbox_id: str = Field(..., description="Unique sandbox tracking identifier")
    target_node: str = Field(..., description="Name of the node under verification")
    commands_executed: List[str] = Field(
        default_factory=list,
        description="Chronological list of candidate patch commands executed",
    )
    all_passed: bool = Field(..., description="True only if all commands succeeded (exit code 0)")
    exit_codes: List[int] = Field(
        default_factory=list,
        description="List of integer exit codes corresponding to commands_executed",
    )
    execution_duration_sec: float = Field(
        default=0.0,
        description="Total verification duration in seconds",
    )
    network_isolated: bool = Field(
        default=True,
        description="Must be True: verifies --network none was strictly enforced",
    )
    resource_quotas: Dict[str, Any] = Field(
        default_factory=dict,
        description="Enforced resource quotas (cpu, mem, pids)",
    )
    timestamp: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat(),
        description="UTC timestamp of report generation",
    )
    pass_signature: str = Field(
        default="",
        description="Deterministic cryptographic verification signature (SHA-256)",
    )
    target_platform: Optional[str] = Field(
        default=None,
        description="Target network OS or platform (e.g. 'linux_iptables', 'cisco_acl')",
    )
    output_logs: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Granular step logs with command output and AAL responses",
    )
    error_message: Optional[str] = Field(
        default=None,
        description="Summary error message if verification failed",
    )

    def model_post_init(self, __context: Any) -> None:
        """Ensure pass_signature is calculated if all_passed and pass_signature is empty."""
        super().model_post_init(__context)
        if not self.pass_signature and self.all_passed:
            self.pass_signature = self.compute_pass_signature(
                sandbox_id=self.sandbox_id,
                target_node=self.target_node,
                commands=self.commands_executed,
                exit_codes=self.exit_codes,
                timestamp=self.timestamp,
            )

    @classmethod
    def compute_pass_signature(
        cls,
        sandbox_id: str,
        target_node: str,
        commands: List[str],
        exit_codes: List[int],
        timestamp: str,
    ) -> str:
        """Compute deterministic SHA-256 verification signature."""
        payload = f"{sandbox_id}:{target_node}:{json.dumps(commands)}:{json.dumps(exit_codes)}:{timestamp}"
        return hashlib.sha256(payload.encode("utf-8")).hexdigest()[:32]

    def verify_clean_pass(self) -> bool:
        """Enforces all criteria required to unlock live deployment."""
        if not self.all_passed:
            return False
        if not getattr(self, "network_isolated", True):
            return False
        if not self.commands_executed:
            return False
        if self.exit_codes and not all(c == 0 for c in self.exit_codes):
            return False
        if self.pass_signature:
            expected_sig = self.compute_pass_signature(
                sandbox_id=self.sandbox_id,
                target_node=self.target_node,
                commands=self.commands_executed,
                exit_codes=self.exit_codes,
                timestamp=self.timestamp,
            )
            if self.pass_signature != expected_sig:
                return False
        return True

